all:	Monster.java Illus.java Tuple.java \
        LensBase.java LensPix.java LensPrior.java LensData.java \
        LensPost.java Lens.java Lenses.java \
	UBase.java Unicorn.java Synth.java Synthimg.java \
        CurveBin.java Complex.java CurveLine.java ComplexExtend.java\
        PlotPix.java PlotMass.java PlotPoten.java PlotArriv.java \
        Poten.java Shear.java Cosm.java Simpwalk.java
	$(JAVAC) Monster.java


Monster.java: Monster.w
	javatangle Monster.w

Illus.java: Illus.w
	javatangle Illus.w

UBase.java: UBase.w
	javatangle UBase.w

Unicorn.java: Unicorn.w
	javatangle Unicorn.w

Synth.java: Synth.w
	javatangle Synth.w

Synthimg.java: Synthimg.w
	javatangle Synthimg.w

Tuple.java: Tuple.w
	javatangle Tuple.w

LensBase.java: LensBase.w
	javatangle LensBase.w

LensPix.java: LensPix.w
	javatangle LensPix.w

LensPrior.java: LensPrior.w
	javatangle LensPrior.w

LensData.java: LensData.w
	javatangle LensData.w

LensPost.java: LensPost.w
	javatangle LensPost.w

Lens.java: Lens.w
	javatangle Lens.w

Lenses.java: Lenses.w
	javatangle Lenses.w

PlotPix.java: PlotPix.w
	javatangle PlotPix.w

PlotMass.java: PlotMass.w
	javatangle PlotMass.w

PlotPoten.java: PlotPoten.w
	javatangle PlotPoten.w

PlotArriv.java: PlotArriv.w
	javatangle PlotArriv.w

Poten.java: Poten.w
	javatangle Poten.w

Shear.java: Shear.w
	javatangle Shear.w

Cosm.java: Cosm.w
	javatangle Cosm.w

Simpwalk.java: Simpwalk.w
	javatangle Simpwalk.w

Complex.java:Complex.w
	javatangle Complex.w

CurveBin.java:CurveBin.w 
	javatangle CurveBin.w
    
CurveLine.java: CurveLine.w
	javatangle CurveLine.w  

ComplexExtend.java: ComplexExtend.w
	javatangle ComplexExtend.w


clean:
	rm -f *.class *.log *.dvi *.toc *.tex *.java *~


